### ISSUE TITLE
using utcOffset throws error: Invalid time zone specified

### ISSUE THREAD

**Issue by isimisi** [Hexagon/croner#245]
**Describe the bug**
When I tried to provide a utcOffset in the config, it threw the error:

```bash

Invalid time zone specified: 120
          at Date.toLocaleString (<anonymous>)
          at getTimezoneOffset (file:///Users/user/project/node_modules/croner/dist/croner.min.js:1:1271)
          at minitz.fromTZ (file:///Users/user/project/node_modules/croner/dist/croner.min.js:1:346)
          at minitz.fromTZISO (file:///Users/user/project/node_modules/croner/dist/croner.min.js:1:177)
          at CronDate.fromString (file:///Users/user/project/node_modules/croner/dist/croner.min.js:1:14933)
          at new CronDate (file:///Users/user/project/node_modules/croner/dist/croner.min.js:1:12735)
          at new Cron (file:///Users/user/project/node_modules/croner/dist/croner.min.js:1:18754)
          at Cron (file:///Users/user/project/node_modules/croner/dist/croner.min.js:1:17812)
          at Playground.run (file:///user/project/commands/playground.ts:14:9)

```

**To Reproduce**
```ts

// using utc offset UTC+02:00
Cron("2024-04-08T11:26:00", { utcOffset: 2 * 60 }, () => {
    console.log("hello world");
});

```

**Expected behavior**
Expected to use the UTC timezone UTC+02:00 and run how you normally would expect the job to run.

**System:**
 - OS: iOS
 - Runtime: tried on both Node.js and Chrome (jsfiddle)
 - Version: 8.0.1

**Comment by Hexagon** [comment]
Verified, will have a look when i find time 👍

**Comment by Hexagon** [comment]
Should be fixed, reopen if not working as expected 👍
